name: pandas_ai_ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pip install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          poetry install
          pip install pylint pytest
      - name: Lint with pylint
        run: |
            pylint $(git ls-files '*.py')
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest
